on:
  workflow_dispatch: {}

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.7"
      - uses: snyk/actions/setup@master
      - run: |
          terraform init -upgrade
          terraform plan -out=tfplan.bin
          terraform show -json tfplan.bin > tfplan.json
          snyk iac test tfplan.json
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
